"""P1 domain core: users crews members invites charters children consents

Revision ID: 8cf7cacb91df
Revises: 
Create Date: 2026-08-28 15:08:21.918674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf7cacb91df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crew_id', sa.String(length=36), nullable=False),
    sa.Column('settlement_mode', sa.String(length=10), nullable=False),
    sa.Column('credit_price_krw', sa.Integer(), nullable=False),
    sa.Column('host_fee_krw', sa.Integer(), nullable=False),
    sa.Column('no_show_fine_krw', sa.Integer(), nullable=False),
    sa.Column('care_rules', sa.String(length=2000), nullable=False),
    sa.Column('handoff_method', sa.String(length=500), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_id')
    )
    op.create_table('children',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guardian_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_year_month', sa.String(length=7), nullable=False),
    sa.Column('traits', sa.String(length=1000), nullable=False),
    sa.Column('allergies', sa.String(length=1000), nullable=False),
    sa.Column('medication', sa.String(length=1000), nullable=False),
    sa.Column('emergency_contact', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crew_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('liability_ack', sa.Boolean(), nullable=False),
    sa.Column('photo_consent', sa.Boolean(), nullable=False),
    sa.Column('guardian_consent', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_id', 'user_id')
    )
    op.create_table('crew_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crew_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_id', 'user_id')
    )
    op.create_table('invites',
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('crew_id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False),
    sa.Column('used_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    op.drop_table('crew_members')
    op.drop_table('consents')
    op.drop_table('children')
    op.drop_table('charters')
    op.drop_table('users')
    op.drop_table('crews')
    # ### end Alembic commands ###
